language: php

before_script:
  - composer self-update
  - composer install --dev --prefer-dist

script:
  - ./phpcs --warning-severity=0 --standard=PSR2 src
  - ./phpunit tests

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
